"""
Generate single-node Python (polars + delta-rs) code from parsed M representation.

This is the `--target python` sibling of pyspark_generator.PySparkGenerator. It
consumes the *same* MParser intermediate representation and emits polars idioms
for the Fabric Python-notebook runtime (no Spark session).

Source of truth for the mapping: _Research/python-notebook-engine-implementation.md
§4 (PySpark -> Python translation reference). Default engine = polars; delta-rs
(`deltalake`) for the Delta write; mount paths (`/lakehouse/default/Tables/...`)
for table I/O.

Design parity with the PySpark generator:
- Original M code preserved as comments.
- snake_case naming.
- DataFrame variable `df` reassigned each step for readability.
- Unknown / unsupported M degrades to a `# TODO` marker, never a crash.
- Connection strings / credentials never appear in executable code (only in
  commentary), matching the existing security behaviour.
"""

import re
from datetime import date
from function_map import (
    get_polars_type,
    get_polars_join_type,
    get_polars_agg,
    get_sort_order,
    M_TO_POLARS_TEXT,
)


class PolarsGenerator:
    """Generates Python/polars code from parsed M intermediate representation."""

    def generate(self, parsed: dict, table_name: str, source_file: str = "") -> str:
        """Generate a complete polars notebook-source file.

        Args:
            parsed: Output from MParser.parse().
            table_name: Name of the table being converted.
            source_file: Original TMDL source file name.

        Returns:
            Complete Python (polars) code as a string.
        """
        sections = []
        sections.append(self._generate_header(table_name, source_file))
        sections.append(self._generate_parameters(table_name, parsed))
        sections.append(self._generate_imports())

        steps = parsed["steps"]
        skip_indices = set()

        for i, step in enumerate(steps):
            if i in skip_indices:
                continue

            if step["type"] == "join" and i + 1 < len(steps) and steps[i + 1]["type"] == "expand_join":
                sections.append(self._generate_join(step, steps[i + 1]))
                skip_indices.add(i + 1)
            else:
                code = self._generate_step(step)
                if code:
                    sections.append(code)

        sections.append(self._generate_write(table_name))

        return "\n\n".join(sections) + "\n"

    def _generate_header(self, table_name: str, source_file: str) -> str:
        snake_name = self._to_snake_case(table_name)
        lines = [
            f"# Converted query: {snake_name}",
            f"# Converted from: {source_file}" if source_file else None,
            "# Original: Power Query M partition",
            "# Engine: Python (polars + delta-rs) single-node",
            f"# Conversion date: {date.today().isoformat()}",
            "#",
            "# NOTE: Auto-generated by m-to-pyspark-converter (--target python).",
            "# This snippet is LAYER-AGNOSTIC: the bronze/silver builder decides the",
            "# notebook layer and sets the real write mode (bronze=append+merge,",
            "# silver=overwrite+overwrite). The write block below is a default.",
            "# table_path() and read_bronze() are provided by the utilities notebook,",
            "# imported at the top of a real notebook via: %run utilities/nb_utils_config",
            "# Review and adjust connection details and business logic before use.",
        ]
        return "\n".join(l for l in lines if l is not None)

    def _generate_parameters(self, table_name: str, parsed: dict) -> str:
        snake_name = self._to_snake_case(table_name)
        lines = ["# --- Parameters ---"]
        lines.append(f'source_table = "{table_name}"')
        lines.append(f'target_table = "bronze_{snake_name}"')

        for param in parsed.get("parameters", []):
            safe_name = self._to_snake_case(param)
            lines.append(f'{safe_name} = ""  # TODO: Set Power Query parameter value for "{param}"')

        return "\n".join(lines)

    def _generate_imports(self) -> str:
        return "\n".join([
            "# --- Imports ---",
            "import polars as pl",
            "from deltalake import write_deltalake, DeltaTable",
        ])

    def _generate_step(self, step: dict) -> str:
        """Dispatch to the appropriate step generator."""
        step_type = step["type"]
        generator = getattr(self, f"_gen_{step_type}", None)
        if generator:
            return generator(step)
        return self._gen_unknown(step)

    # --- Source & Navigation ---

    def _gen_source(self, step: dict) -> str:
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: {self._truncate(step['raw'])}")

        func = step.get("function", "")
        args = step.get("args", {})

        if func in ("Sql.Database", "Sql.Databases"):
            server = args.get("server", "")
            db = args.get("database", "")
            # Connection details are echoed only as a comment, never as executable code.
            lines.append(f"# Original source: {func}({server!r}, {db!r})")
            lines.append("# TODO: Configure Fabric lakehouse / SQL source connection")
            lines.append("# Replace with: pl.read_delta(table_path(source_table))")
            lines.append("df = pl.read_delta(table_path(source_table))")
        elif func == "Csv.Document":
            lines.append("# TODO: Update path for Fabric Files mount location")
            lines.append('df = pl.read_csv(f"/lakehouse/default/Files/{source_table}.csv")')
        elif func in ("Excel.Workbook", "Excel.CurrentWorkbook"):
            lines.append("# TODO: Excel requires a reader (fastexcel/openpyxl) or convert to CSV/Parquet first")
            lines.append(f"# Original: {func}")
            lines.append("df = pl.read_delta(table_path(source_table))")
        else:
            lines.append(f"# TODO: Unsupported source type: {func}")
            lines.append("# Configure Fabric lakehouse connection manually")
            lines.append("df = pl.read_delta(table_path(source_table))")

        return "\n".join(lines)

    def _gen_navigation(self, step: dict) -> str:
        schema = step.get("schema", "dbo")
        table = step.get("table", "")
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: {self._truncate(step['raw'])}")
        if schema and table:
            lines.append(f"# Original: [{schema}].[{table}]")
        if table:
            snake = self._to_snake_case(table)
            lines.append(f'df = pl.read_delta(table_path("{snake}"))')
        return "\n".join(lines)

    # --- Transformations ---

    def _gen_filter(self, step: dict) -> str:
        condition = step.get("condition", "")
        polars_cond = self._convert_condition(condition)
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.SelectRows(..., each {condition})")
        lines.append(f"df = df.filter({polars_cond})")
        return "\n".join(lines)

    def _gen_add_column(self, step: dict) -> str:
        col_name = step.get("column_name", "NewColumn")
        expression = step.get("expression", "")
        col_type = step.get("column_type")
        polars_expr = self._convert_each_expression(expression)

        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f'# M: Table.AddColumn(..., "{col_name}", each {expression})')
        if col_type:
            polars_type = get_polars_type(col_type)
            lines.append(f'df = df.with_columns(({polars_expr}).cast({polars_type}).alias("{col_name}"))')
        else:
            lines.append(f'df = df.with_columns(({polars_expr}).alias("{col_name}"))')
        return "\n".join(lines)

    def _gen_rename(self, step: dict) -> str:
        renames = step.get("renames", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.RenameColumns(...)")
        if renames:
            mapping = ", ".join(f'"{old}": "{new}"' for old, new in renames)
            lines.append(f"df = df.rename({{{mapping}}})")
        return "\n".join(lines)

    def _gen_remove_columns(self, step: dict) -> str:
        columns = step.get("columns", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.RemoveColumns(...)")
        cols_str = ", ".join(f'"{c}"' for c in columns)
        lines.append(f"df = df.drop({cols_str})")
        return "\n".join(lines)

    def _gen_select_columns(self, step: dict) -> str:
        columns = step.get("columns", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.SelectColumns(...)")
        cols_str = ", ".join(f'"{c}"' for c in columns)
        lines.append(f"df = df.select({cols_str})")
        return "\n".join(lines)

    def _gen_change_types(self, step: dict) -> str:
        type_changes = step.get("type_changes", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.TransformColumnTypes(...)")
        if type_changes:
            lines.append("df = df.with_columns(")
            for i, (col, m_type) in enumerate(type_changes):
                polars_type = get_polars_type(m_type)
                comma = "," if i < len(type_changes) - 1 else ""
                lines.append(f'    pl.col("{col}").cast({polars_type}){comma}')
            lines.append(")")
        return "\n".join(lines)

    def _gen_sort(self, step: dict) -> str:
        sorts = step.get("sorts", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.Sort(...)")
        if sorts:
            cols = ", ".join(f'"{col}"' for col, _ in sorts)
            descending = [get_sort_order(order) == "desc" for _, order in sorts]
            if all(descending):
                lines.append(f"df = df.sort({cols}, descending=True)")
            elif not any(descending):
                lines.append(f"df = df.sort({cols})")
            else:
                desc_list = ", ".join("True" if d else "False" for d in descending)
                lines.append(f"df = df.sort([{cols}], descending=[{desc_list}])")
        return "\n".join(lines)

    def _gen_group_by(self, step: dict) -> str:
        group_cols = step.get("group_columns", [])
        aggregations = step.get("aggregations", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.Group(...)")

        group_str = ", ".join(f'"{c}"' for c in group_cols)
        agg_parts = []
        for agg in aggregations:
            agg_parts.append(self._convert_aggregation(agg["expression"], agg["name"]))

        if agg_parts:
            lines.append(f"df = df.group_by({group_str}).agg(")
            for i, part in enumerate(agg_parts):
                comma = "," if i < len(agg_parts) - 1 else ""
                lines.append(f"    {part}{comma}")
            lines.append(")")
        else:
            lines.append(f"df = df.group_by({group_str}).agg(pl.len().alias(\"count\"))")

        return "\n".join(lines)

    def _generate_join(self, join_step: dict, expand_step: dict) -> str:
        """Generate a combined join + expand as a polars join."""
        right_table = join_step.get("right_table", "")
        left_key = join_step.get("left_key", [])
        right_key = join_step.get("right_key", [])
        join_kind = join_step.get("join_kind", "JoinKind.LeftOuter")
        polars_how = get_polars_join_type(join_kind)

        expand_cols = expand_step.get("columns", [])
        aliases = expand_step.get("aliases", expand_cols)

        right_snake = self._to_snake_case(right_table)

        lines = [f"# --- Step: {join_step['name']} + {expand_step['name']} ---"]
        lines.append("# M: Table.NestedJoin(...) + Table.ExpandTableColumn(...)")

        lines.append(f'df_{right_snake} = pl.read_delta(table_path("{right_snake}"))')
        if join_kind == "JoinKind.RightAnti":
            lines.append("# TODO: RightAnti has no direct polars 'how' - using 'anti' (left-anti); "
                         "swap operands if you need right-anti semantics")

        if left_key and right_key:
            if left_key == right_key:
                on = self._key_repr(left_key)
                lines.append(f'df = df.join(df_{right_snake}, on={on}, how="{polars_how}")')
            else:
                lo = self._key_repr(left_key)
                ro = self._key_repr(right_key)
                lines.append(f'df = df.join(df_{right_snake}, left_on={lo}, right_on={ro}, how="{polars_how}")')
        else:
            lines.append("# TODO: specify join keys")
            lines.append(f'df = df.join(df_{right_snake}, how="{polars_how}")')

        if expand_cols and aliases:
            for orig, alias in zip(expand_cols, aliases):
                if orig != alias:
                    lines.append(f'df = df.rename({{"{orig}": "{alias}"}})')

        return "\n".join(lines)

    def _gen_join(self, step: dict) -> str:
        """Generate join without an expand (standalone)."""
        right_table = step.get("right_table", "")
        left_key = step.get("left_key", [])
        right_key = step.get("right_key", [])
        join_kind = step.get("join_kind", "JoinKind.LeftOuter")
        polars_how = get_polars_join_type(join_kind)

        right_snake = self._to_snake_case(right_table)

        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: {self._truncate(step['raw'])}")
        lines.append(f'df_{right_snake} = pl.read_delta(table_path("{right_snake}"))')

        if left_key and right_key:
            if left_key == right_key:
                on = self._key_repr(left_key)
                lines.append(f'df = df.join(df_{right_snake}, on={on}, how="{polars_how}")')
            else:
                lo = self._key_repr(left_key)
                ro = self._key_repr(right_key)
                lines.append(f'df = df.join(df_{right_snake}, left_on={lo}, right_on={ro}, how="{polars_how}")')
        else:
            lines.append("# TODO: specify join keys")
            lines.append(f'df = df.join(df_{right_snake}, how="{polars_how}")')
        return "\n".join(lines)

    def _key_repr(self, keys: list) -> str:
        """Render a single key as a string literal, multiple as a list literal."""
        if len(keys) == 1:
            return f'"{keys[0]}"'
        return "[" + ", ".join(f'"{k}"' for k in keys) + "]"

    def _gen_expand_join(self, step: dict) -> str:
        """Generate expand as renames (when no preceding join was merged)."""
        columns = step.get("columns", [])
        aliases = step.get("aliases", columns)
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.ExpandTableColumn(...)")
        lines.append("# TODO: This expand was not paired with a join - review manually")
        for orig, alias in zip(columns, aliases):
            if orig != alias:
                lines.append(f'df = df.rename({{"{orig}": "{alias}"}})')
        return "\n".join(lines)

    def _gen_distinct(self, step: dict) -> str:
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.Distinct(...)")
        lines.append("df = df.unique()")
        return "\n".join(lines)

    def _gen_union(self, step: dict) -> str:
        tables = step.get("tables", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.Combine({...})")
        for t in tables:
            snake = self._to_snake_case(t)
            lines.append(f'df_{snake} = pl.read_delta(table_path("{snake}"))')
        if tables:
            frames = ", ".join(["df"] + [f"df_{self._to_snake_case(t)}" for t in tables])
            lines.append(f'df = pl.concat([{frames}], how="diagonal_relaxed")')
        return "\n".join(lines)

    def _gen_replace_value(self, step: dict) -> str:
        old_val = step.get("old_value", "")
        new_val = step.get("new_value", "")
        columns = step.get("columns", [])
        replacer = step.get("replacer", "text")

        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.ReplaceValue(...)")

        if old_val == "null" or old_val == "":
            for col in columns:
                lines.append(
                    f'df = df.with_columns(pl.col("{col}").fill_null({self._py_literal(new_val)}))'
                )
        elif replacer == "text":
            for col in columns:
                lines.append(
                    f'df = df.with_columns('
                    f'pl.col("{col}").str.replace_all({self._py_literal(old_val)}, '
                    f'{self._py_literal(new_val)}, literal=True))'
                )
        else:
            for col in columns:
                lines.append(
                    f'df = df.with_columns('
                    f'pl.when(pl.col("{col}") == {self._py_literal(old_val)})'
                    f'.then({self._py_literal(new_val)})'
                    f'.otherwise(pl.col("{col}")).alias("{col}"))'
                )
        return "\n".join(lines)

    def _gen_fill_down(self, step: dict) -> str:
        columns = step.get("columns", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.FillDown(...)")
        if columns:
            exprs = ", ".join(f'pl.col("{c}").forward_fill()' for c in columns)
            lines.append(f"df = df.with_columns({exprs})")
        return "\n".join(lines)

    def _gen_fill_up(self, step: dict) -> str:
        columns = step.get("columns", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.FillUp(...)")
        if columns:
            exprs = ", ".join(f'pl.col("{c}").backward_fill()' for c in columns)
            lines.append(f"df = df.with_columns({exprs})")
        return "\n".join(lines)

    def _gen_pivot(self, step: dict) -> str:
        pivot_col = step.get("pivot_column", "")
        value_col = step.get("value_column", "")
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.Pivot(...)")
        lines.append("# TODO: Review pivot - specify index (group-by) columns")
        lines.append(
            f'df = df.pivot("{pivot_col}", values="{value_col}", aggregate_function="first")'
        )
        return "\n".join(lines)

    def _gen_unpivot(self, step: dict) -> str:
        columns = step.get("columns", [])
        attr_col = step.get("attribute_column", "Attribute")
        val_col = step.get("value_column", "Value")
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.Unpivot(...)")
        cols_str = ", ".join(f'"{c}"' for c in columns)
        lines.append(
            f"df = df.unpivot(on=[{cols_str}], "
            f"variable_name={attr_col!r}, value_name={val_col!r})"
        )
        return "\n".join(lines)

    def _gen_unpivot_other(self, step: dict) -> str:
        return self._gen_unpivot(step)

    def _gen_duplicate_column(self, step: dict) -> str:
        src = step.get("source_column", "")
        new = step.get("new_column", "")
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.DuplicateColumn(...)")
        lines.append(f'df = df.with_columns(pl.col("{src}").alias("{new}"))')
        return "\n".join(lines)

    def _gen_first_n(self, step: dict) -> str:
        n = step.get("n", 1)
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.FirstN(..., {n})")
        lines.append(f"df = df.head({n})")
        return "\n".join(lines)

    def _gen_last_n(self, step: dict) -> str:
        n = step.get("n", 1)
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.LastN(..., {n})")
        lines.append(f"df = df.tail({n})")
        return "\n".join(lines)

    def _gen_skip(self, step: dict) -> str:
        n = step.get("n", 1)
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.Skip/RemoveFirstN(..., {n})")
        lines.append(f"df = df.slice({n})")
        return "\n".join(lines)

    def _gen_cache(self, step: dict) -> str:
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.Buffer(...)")
        lines.append("# polars is eager by default; Buffer is a no-op (collect a LazyFrame if needed)")
        lines.append("df = df  # buffered")
        return "\n".join(lines)

    def _gen_transform_columns(self, step: dict) -> str:
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: {self._truncate(step['raw'])}")
        lines.append("# TODO: Table.TransformColumns - review and convert manually")
        return "\n".join(lines)

    def _gen_promote_headers(self, step: dict) -> str:
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.PromoteHeaders(...)")
        lines.append("# TODO: PromoteHeaders - typically handled at read time with has_header=True")
        return "\n".join(lines)

    def _gen_remove_last_n(self, step: dict) -> str:
        n = step.get("n", 1)
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.RemoveLastN(..., {n})")
        lines.append(f"df = df.head(df.height - {n})")
        return "\n".join(lines)

    def _gen_unknown(self, step: dict) -> str:
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# TODO: Could not auto-convert this step. Original M code:")
        for raw_line in step["raw"].split("\n"):
            lines.append(f"#   {raw_line}")
        lines.append("# df = df  # Placeholder - implement manually")
        return "\n".join(lines)

    # --- Write ---

    def _generate_write(self, table_name: str) -> str:
        return "\n".join([
            "# --- Write ---",
            "# NOTE: layer-agnostic default below — the bronze/silver builder sets the",
            "# real layer write mode. Bronze: mode=\"append\", schema_mode=\"merge\".",
            "# Silver: mode=\"overwrite\", schema_mode=\"overwrite\". (write_mode is the",
            "# builder-overridden default.)",
            'write_mode = "overwrite"  # TODO: builder sets layer write mode',
            'schema_write_mode = "overwrite"  # TODO: builder sets layer schema mode',
            "write_deltalake(",
            "    table_path(target_table),",
            "    df.to_arrow(),",
            "    mode=write_mode,",
            "    schema_mode=schema_write_mode,",
            ")",
        ])

    # --- Expression converters ---

    def _convert_condition(self, m_condition: str) -> str:
        """Convert an M filter condition to a polars boolean expression."""
        expr = m_condition.strip()

        # Null checks
        expr = re.sub(r'\[([^\]]+)\]\s*=\s*null', r'pl.col("\1").is_null()', expr)
        expr = re.sub(r'\[([^\]]+)\]\s*<>\s*null', r'pl.col("\1").is_not_null()', expr)

        # [Column] = "value"
        expr = re.sub(
            r'\[([^\]]+)\]\s*=\s*"([^"]*)"',
            r'(pl.col("\1") == "\2")',
            expr,
        )
        expr = re.sub(
            r'\[([^\]]+)\]\s*<>\s*"([^"]*)"',
            r'(pl.col("\1") != "\2")',
            expr,
        )

        # [Column] = number
        expr = re.sub(
            r'\[([^\]]+)\]\s*=\s*(\d+(?:\.\d+)?)',
            r'(pl.col("\1") == \2)',
            expr,
        )
        expr = re.sub(
            r'\[([^\]]+)\]\s*<>\s*(\d+(?:\.\d+)?)',
            r'(pl.col("\1") != \2)',
            expr,
        )

        # Comparison operators
        expr = re.sub(
            r'\[([^\]]+)\]\s*(>=|<=|>|<)\s*(\d+(?:\.\d+)?)',
            r'(pl.col("\1") \2 \3)',
            expr,
        )

        # Text.Contains / StartsWith / EndsWith
        expr = re.sub(
            r'Text\.Contains\(\[([^\]]+)\],\s*"([^"]*)"\)',
            r'pl.col("\1").str.contains("\2", literal=True)',
            expr,
        )
        expr = re.sub(
            r'Text\.StartsWith\(\[([^\]]+)\],\s*"([^"]*)"\)',
            r'pl.col("\1").str.starts_with("\2")',
            expr,
        )
        expr = re.sub(
            r'Text\.EndsWith\(\[([^\]]+)\],\s*"([^"]*)"\)',
            r'pl.col("\1").str.ends_with("\2")',
            expr,
        )

        # Logical operators
        expr = expr.replace(" and ", " & ")
        expr = expr.replace(" or ", " | ")

        # Remaining [Column] references
        expr = re.sub(r'\[([^\]]+)\]', r'pl.col("\1")', expr)

        return expr

    def _convert_each_expression(self, m_expr: str) -> str:
        """Convert an M 'each' expression body to a polars column expression."""
        expr = m_expr.strip()

        # if/then/else (including nested `else if`) -> chained
        # pl.when().then()...otherwise(). A single-level if produces exactly
        # pl.when(c).then(v).otherwise(e) (unchanged from the original).
        if re.match(r'if\s', expr):
            chain = self._convert_if_chain(expr)
            if chain:
                return chain

        # [Column]
        col_match = re.match(r'^\[([^\]]+)\]$', expr)
        if col_match:
            return f'pl.col("{col_match.group(1)}")'

        # [Col1] & [Col2] (string concat) -> pl.concat_str
        if "&" in expr and not re.search(r'[*+\-/]', expr):
            parts = expr.split("&")
            converted = [self._convert_value(p.strip()) for p in parts]
            return f"pl.concat_str([{', '.join(converted)}])"

        # Text.* function calls
        text_match = re.match(r'Text\.(\w+)\((.+)\)', expr)
        if text_match:
            return self._convert_text_function(text_match.group(1), text_match.group(2))

        # Arithmetic with [Column] references
        if re.search(r'\[[^\]]+\]', expr) and re.search(r'[*+\-/]', expr):
            converted = re.sub(r'\[([^\]]+)\]', r'pl.col("\1")', expr)
            converted = re.sub(r'#"([^"]+)"', r'pl.col("\1")', converted)
            return converted

        # Simple column reference
        expr = re.sub(r'\[([^\]]+)\]', r'pl.col("\1")', expr)

        # #"Quoted" references
        expr = re.sub(r'#"([^"]+)"', r'pl.col("\1")', expr)

        # String literal
        if expr.startswith('"') and expr.endswith('"'):
            return f"pl.lit({expr})"

        # Numeric literal
        if re.match(r'^-?\d+(\.\d+)?$', expr):
            return f"pl.lit({expr})"

        # Fallback
        return f'pl.lit(None)  # TODO: Review expression: {self._truncate(expr)}'

    def _convert_if_chain(self, expr: str) -> str:
        """Convert a (possibly nested) M if/then/else into a chained polars
        when/then expression: pl.when(c1).then(v1).when(c2).then(v2)...otherwise(e).

        Recurses on the `else` branch so nested `else if` becomes additional
        .when().then() links rather than being dumped into a string literal
        (the IMP-1 SyntaxError). Returns "" if expr is not a well-formed if so
        the caller can fall through to other handlers.
        """
        branches = []  # (cond, then) pairs
        rest = expr.strip()
        while True:
            m = re.match(r'if\s+(.+?)\s+then\s+(.+?)\s+else\s+(.+)', rest, re.DOTALL)
            if not m:
                return ""
            cond = self._convert_condition(m.group(1).strip())
            then_val = self._convert_value(m.group(2).strip())
            branches.append((cond, then_val))
            rest = m.group(3).strip()
            if not re.match(r'if\s', rest):
                else_val = self._convert_value(rest)
                break
        chain = f"pl.when({branches[0][0]}).then({branches[0][1]})"
        for cond, then_val in branches[1:]:
            chain += f".when({cond}).then({then_val})"
        chain += f".otherwise({else_val})"
        return chain

    def _convert_value(self, val: str) -> str:
        """Convert an M value to a polars literal or column ref."""
        val = val.strip()
        if val == "null":
            return "pl.lit(None)"
        if val.startswith('"') and val.endswith('"'):
            return f"pl.lit({val})"
        if re.match(r'^-?\d+(\.\d+)?$', val):
            return f"pl.lit({val})"
        col_match = re.match(r'^\[([^\]]+)\]$', val)
        if col_match:
            return f'pl.col("{col_match.group(1)}")'
        # Fallback: embed as a string literal, escaping quotes/backslashes so an
        # unexpected value can never break Python syntax (IMP-1 hardening).
        escaped = val.replace("\\", "\\\\").replace('"', '\\"')
        return f'pl.lit("{escaped}")'

    def _convert_text_function(self, func: str, args: str) -> str:
        """Convert a Text.* function call to a polars str expression."""
        method = M_TO_POLARS_TEXT.get(f"Text.{func}")
        if method:
            col = self._extract_col_ref(args)
            return f"{col}.str.{method}()"
        if func == "Replace":
            parts = args.split(",", 2)
            col = self._extract_col_ref(parts[0])
            old = parts[1].strip() if len(parts) > 1 else '""'
            new = parts[2].strip() if len(parts) > 2 else '""'
            return f"{col}.str.replace_all({old}, {new}, literal=True)"
        return f'pl.lit(None)  # TODO: Convert Text.{func} manually'

    def _extract_col_ref(self, text: str) -> str:
        """Extract a polars column reference from text."""
        text = text.strip()
        col_match = re.match(r'\[([^\]]+)\]', text)
        if col_match:
            return f'pl.col("{col_match.group(1)}")'
        return f'pl.col("{text}")'

    def _convert_aggregation(self, m_agg_expr: str, agg_name: str) -> str:
        """Convert an M aggregation expression to a polars agg expression."""
        m_agg_expr = m_agg_expr.strip()

        # List.Sum([Column]) etc.
        agg_match = re.match(r'(List\.\w+)\(\[([^\]]+)\]\)', m_agg_expr)
        if agg_match:
            method = get_polars_agg(agg_match.group(1))
            col = agg_match.group(2)
            return f'pl.col("{col}").{method}().alias("{agg_name}")'

        # List.Count(each ...) / Table.RowCount -> count of rows
        if "List.Count" in m_agg_expr or "Table.RowCount" in m_agg_expr:
            return f'pl.len().alias("{agg_name}")'

        return f'pl.lit("TODO").alias("{agg_name}")  # TODO: {self._truncate(m_agg_expr)}'

    # --- Utilities ---

    def _polars_type(self, m_type: str) -> str:
        """Resolve an M type string to a polars dtype expression (default pl.Utf8)."""
        return get_polars_type(m_type)

    def _to_snake_case(self, name: str) -> str:
        """Convert a name to snake_case."""
        name = re.sub(r'[^a-zA-Z0-9\s_]', '', name)
        name = re.sub(r'([a-z])([A-Z])', r'\1_\2', name)
        name = re.sub(r'[\s]+', '_', name)
        return name.lower().strip('_')

    def _truncate(self, text: str, max_len: int = 100) -> str:
        """Truncate text for display in comments."""
        text = text.replace("\n", " ").strip()
        if len(text) <= max_len:
            return text
        return text[:max_len] + "..."

    def _py_literal(self, val: str) -> str:
        """Convert an M value to a Python literal string."""
        if val == "null":
            return "None"
        if re.match(r'^-?\d+(\.\d+)?$', val):
            return val
        return f'"{val}"'
