"""
Generate PySpark code from parsed M representation.

Produces .py files following Fabric notebook conventions:
- F. alias for pyspark.sql.functions
- snake_case naming
- Method chaining with backslash continuation
- DataFrame variable reassigned each step for readability
- Original M code preserved as comments
"""

import re
from datetime import date
from function_map import (
    get_pyspark_type,
    get_join_type,
    get_sort_order,
    get_agg_function,
    M_OPERATORS,
)


class PySparkGenerator:
    """Generates PySpark code from parsed M intermediate representation."""

    def generate(self, parsed: dict, table_name: str, source_file: str = "") -> str:
        """Generate a complete PySpark notebook file.

        Args:
            parsed: Output from MParser.parse().
            table_name: Name of the table being converted.
            source_file: Original TMDL source file name.

        Returns:
            Complete PySpark code as a string.
        """
        sections = []
        sections.append(self._generate_header(table_name, source_file))
        sections.append(self._generate_parameters(table_name, parsed))
        sections.append(self._generate_imports())

        # Track join expand pairs for combined generation
        steps = parsed["steps"]
        skip_indices = set()

        for i, step in enumerate(steps):
            if i in skip_indices:
                continue

            if step["type"] == "join" and i + 1 < len(steps) and steps[i + 1]["type"] == "expand_join":
                sections.append(self._generate_join(step, steps[i + 1]))
                skip_indices.add(i + 1)
            else:
                code = self._generate_step(step)
                if code:
                    sections.append(code)

        sections.append(self._generate_write(table_name))

        return "\n\n".join(sections) + "\n"

    def _generate_header(self, table_name: str, source_file: str) -> str:
        snake_name = self._to_snake_case(table_name)
        lines = [
            f"# Notebook: nb_bronze_{snake_name}",
            f"# Converted from: {source_file}" if source_file else None,
            "# Original: Power Query M partition",
            f"# Conversion date: {date.today().isoformat()}",
            "#",
            "# NOTE: Auto-generated by m-to-pyspark-converter.",
            "# Review and adjust connection details and business logic before use.",
        ]
        return "\n".join(l for l in lines if l is not None)

    def _generate_parameters(self, table_name: str, parsed: dict) -> str:
        snake_name = self._to_snake_case(table_name)
        lines = ["# --- Parameters ---"]
        lines.append(f'source_table = "{table_name}"')
        lines.append(f'target_table = "bronze_{snake_name}"')

        # Add extracted parameters
        for param in parsed.get("parameters", []):
            safe_name = self._to_snake_case(param)
            lines.append(f'{safe_name} = ""  # TODO: Set Power Query parameter value for "{param}"')

        return "\n".join(lines)

    def _generate_imports(self) -> str:
        return "\n".join([
            "# --- Imports ---",
            "from pyspark.sql import functions as F",
            "from pyspark.sql.types import *",
            "from pyspark.sql.window import Window",
        ])

    def _generate_step(self, step: dict) -> str:
        """Dispatch to the appropriate step generator."""
        step_type = step["type"]
        generator = getattr(self, f"_gen_{step_type}", None)
        if generator:
            return generator(step)
        return self._gen_unknown(step)

    # --- Source & Navigation ---

    def _gen_source(self, step: dict) -> str:
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: {self._truncate(step['raw'])}")

        func = step.get("function", "")
        args = step.get("args", {})

        if func in ("Sql.Database", "Sql.Databases"):
            server = args.get("server", "")
            db = args.get("database", "")
            lines.append(f"# Original source: {func}({server!r}, {db!r})")
            lines.append("# TODO: Configure Fabric lakehouse connection")
            lines.append("# Replace with: spark.read.table(source_table)")
            lines.append("df = spark.read.table(source_table)")
        elif func == "Csv.Document":
            lines.append("# TODO: Update path for Fabric Files location")
            lines.append('df = spark.read.format("csv") \\')
            lines.append('    .option("header", True) \\')
            lines.append('    .option("inferSchema", True) \\')
            lines.append('    .load(f"Files/{source_table}.csv")')
        elif func in ("Excel.Workbook", "Excel.CurrentWorkbook"):
            lines.append("# TODO: Excel not natively supported in Spark - convert to CSV/Parquet first")
            lines.append(f"# Original: {func}")
            lines.append("df = spark.read.table(source_table)")
        else:
            lines.append(f"# TODO: Unsupported source type: {func}")
            lines.append("# Configure Fabric lakehouse connection manually")
            lines.append("df = spark.read.table(source_table)")

        return "\n".join(lines)

    def _gen_navigation(self, step: dict) -> str:
        schema = step.get("schema", "dbo")
        table = step.get("table", "")
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: {self._truncate(step['raw'])}")
        if schema and table:
            lines.append(f"# Original: [{schema}].[{table}]")
        if table:
            snake = self._to_snake_case(table)
            lines.append(f'df = spark.read.table("{snake}")')
        return "\n".join(lines)

    # --- Transformations ---

    def _gen_filter(self, step: dict) -> str:
        condition = step.get("condition", "")
        pyspark_cond = self._convert_condition(condition)
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.SelectRows(..., each {condition})")
        lines.append(f"df = df.filter({pyspark_cond})")
        return "\n".join(lines)

    def _gen_add_column(self, step: dict) -> str:
        col_name = step.get("column_name", "NewColumn")
        expression = step.get("expression", "")
        col_type = step.get("column_type")
        pyspark_expr = self._convert_each_expression(expression)

        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f'# M: Table.AddColumn(..., "{col_name}", each {expression})')
        if col_type:
            pyspark_type = get_pyspark_type(col_type)
            lines.append(f'df = df.withColumn("{col_name}", ({pyspark_expr}).cast({pyspark_type}))')
        else:
            lines.append(f'df = df.withColumn("{col_name}", {pyspark_expr})')
        return "\n".join(lines)

    def _gen_rename(self, step: dict) -> str:
        renames = step.get("renames", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.RenameColumns(...)")
        if len(renames) == 1:
            old, new = renames[0]
            lines.append(f'df = df.withColumnRenamed("{old}", "{new}")')
        elif renames:
            lines.append("df = df \\")
            for i, (old, new) in enumerate(renames):
                end = "" if i == len(renames) - 1 else " \\"
                lines.append(f'    .withColumnRenamed("{old}", "{new}"){end}')
        return "\n".join(lines)

    def _gen_remove_columns(self, step: dict) -> str:
        columns = step.get("columns", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.RemoveColumns(...)")
        cols_str = ", ".join(f'"{c}"' for c in columns)
        lines.append(f"df = df.drop({cols_str})")
        return "\n".join(lines)

    def _gen_select_columns(self, step: dict) -> str:
        columns = step.get("columns", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.SelectColumns(...)")
        cols_str = ", ".join(f'"{c}"' for c in columns)
        lines.append(f"df = df.select({cols_str})")
        return "\n".join(lines)

    def _gen_change_types(self, step: dict) -> str:
        type_changes = step.get("type_changes", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.TransformColumnTypes(...)")
        if type_changes:
            lines.append("df = df \\")
            for i, (col, m_type) in enumerate(type_changes):
                pyspark_type = get_pyspark_type(m_type)
                end = "" if i == len(type_changes) - 1 else " \\"
                lines.append(f'    .withColumn("{col}", F.col("{col}").cast({pyspark_type})){end}')
        return "\n".join(lines)

    def _gen_sort(self, step: dict) -> str:
        sorts = step.get("sorts", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.Sort(...)")
        if sorts:
            sort_exprs = []
            for col, order in sorts:
                direction = get_sort_order(order)
                if direction == "desc":
                    sort_exprs.append(f'F.col("{col}").desc()')
                else:
                    sort_exprs.append(f'F.col("{col}").asc()')
            lines.append(f"df = df.orderBy({', '.join(sort_exprs)})")
        return "\n".join(lines)

    def _gen_group_by(self, step: dict) -> str:
        group_cols = step.get("group_columns", [])
        aggregations = step.get("aggregations", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.Group(...)")

        group_str = ", ".join(f'"{c}"' for c in group_cols)
        agg_parts = []
        for agg in aggregations:
            agg_name = agg["name"]
            agg_expr = agg["expression"]
            pyspark_agg = self._convert_aggregation(agg_expr, agg_name)
            agg_parts.append(pyspark_agg)

        if agg_parts:
            lines.append(f"df = df.groupBy({group_str}).agg(")
            for i, part in enumerate(agg_parts):
                comma = "," if i < len(agg_parts) - 1 else ""
                lines.append(f"    {part}{comma}")
            lines.append(")")
        else:
            lines.append(f"df = df.groupBy({group_str}).count()")

        return "\n".join(lines)

    def _generate_join(self, join_step: dict, expand_step: dict) -> str:
        """Generate a combined join + expand as a PySpark join."""
        right_table = join_step.get("right_table", "")
        left_key = join_step.get("left_key", [])
        right_key = join_step.get("right_key", [])
        join_kind = join_step.get("join_kind", "JoinKind.LeftOuter")
        pyspark_how = get_join_type(join_kind)

        expand_cols = expand_step.get("columns", [])
        aliases = expand_step.get("aliases", expand_cols)

        right_snake = self._to_snake_case(right_table)

        lines = [f"# --- Step: {join_step['name']} + {expand_step['name']} ---"]
        lines.append(f"# M: Table.NestedJoin(...) + Table.ExpandTableColumn(...)")

        lines.append(f'df_{right_snake} = spark.read.table("{right_snake}")')
        lines.append("")

        # Build join condition
        if len(left_key) == 1 and len(right_key) == 1:
            cond = f'F.col("{left_key[0]}") == df_{right_snake}["{right_key[0]}"]'
        elif left_key and right_key:
            conds = []
            for lk, rk in zip(left_key, right_key):
                conds.append(f'(F.col("{lk}") == df_{right_snake}["{rk}"])')
            cond = " & ".join(conds)
        else:
            cond = "# TODO: specify join condition"

        lines.append(f"df = df.join(df_{right_snake}, {cond}, {pyspark_how!r})")

        # Select expanded columns with aliases
        if expand_cols and aliases:
            for orig, alias in zip(expand_cols, aliases):
                if orig != alias:
                    lines.append(f'df = df.withColumnRenamed("{orig}", "{alias}")')

        return "\n".join(lines)

    def _gen_join(self, step: dict) -> str:
        """Generate join without an expand (standalone)."""
        right_table = step.get("right_table", "")
        left_key = step.get("left_key", [])
        right_key = step.get("right_key", [])
        join_kind = step.get("join_kind", "JoinKind.LeftOuter")
        pyspark_how = get_join_type(join_kind)

        right_snake = self._to_snake_case(right_table)

        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: {self._truncate(step['raw'])}")
        lines.append(f'df_{right_snake} = spark.read.table("{right_snake}")')

        if len(left_key) == 1 and len(right_key) == 1:
            cond = f'F.col("{left_key[0]}") == df_{right_snake}["{right_key[0]}"]'
        else:
            cond = "# TODO: specify join condition"

        lines.append(f"df = df.join(df_{right_snake}, {cond}, {pyspark_how!r})")
        return "\n".join(lines)

    def _gen_expand_join(self, step: dict) -> str:
        """Generate expand as column selection (when no preceding join was merged)."""
        columns = step.get("columns", [])
        aliases = step.get("aliases", columns)
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.ExpandTableColumn(...)")
        lines.append("# TODO: This expand was not paired with a join - review manually")
        for orig, alias in zip(columns, aliases):
            if orig != alias:
                lines.append(f'df = df.withColumnRenamed("{orig}", "{alias}")')
        return "\n".join(lines)

    def _gen_distinct(self, step: dict) -> str:
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.Distinct(...)")
        lines.append("df = df.distinct()")
        return "\n".join(lines)

    def _gen_union(self, step: dict) -> str:
        tables = step.get("tables", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.Combine({...})")
        for t in tables:
            snake = self._to_snake_case(t)
            lines.append(f'df_{snake} = spark.read.table("{snake}")')
        if tables:
            union_parts = [f"df_{self._to_snake_case(t)}" for t in tables]
            lines.append(f"df = df.unionByName({union_parts[0]})" if len(tables) == 1
                         else f"df = df{''.join(f'.unionByName(df_{self._to_snake_case(t)})' for t in tables)}")
        return "\n".join(lines)

    def _gen_replace_value(self, step: dict) -> str:
        old_val = step.get("old_value", "")
        new_val = step.get("new_value", "")
        columns = step.get("columns", [])
        replacer = step.get("replacer", "text")

        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.ReplaceValue(...)")

        # Handle null replacements
        if old_val == "null" or old_val == "":
            for col in columns:
                lines.append(
                    f'df = df.withColumn("{col}", '
                    f'F.when(F.col("{col}").isNull(), {self._py_literal(new_val)})'
                    f'.otherwise(F.col("{col}")))'
                )
        elif replacer == "text":
            for col in columns:
                lines.append(
                    f'df = df.withColumn("{col}", '
                    f'F.regexp_replace(F.col("{col}"), {self._py_literal(old_val)}, {self._py_literal(new_val)}))'
                )
        else:
            for col in columns:
                lines.append(
                    f'df = df.withColumn("{col}", '
                    f'F.when(F.col("{col}") == {self._py_literal(old_val)}, {self._py_literal(new_val)})'
                    f'.otherwise(F.col("{col}")))'
                )
        return "\n".join(lines)

    def _gen_fill_down(self, step: dict) -> str:
        columns = step.get("columns", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.FillDown(...)")
        lines.append("# TODO: FillDown requires a window with ordering - specify order column")
        lines.append('w = Window.orderBy(F.monotonically_increasing_id()).rowsBetween(Window.unboundedPreceding, 0)')
        for col in columns:
            lines.append(f'df = df.withColumn("{col}", F.last(F.col("{col}"), ignorenulls=True).over(w))')
        return "\n".join(lines)

    def _gen_fill_up(self, step: dict) -> str:
        columns = step.get("columns", [])
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.FillUp(...)")
        lines.append("# TODO: FillUp requires a window with ordering - specify order column")
        lines.append('w = Window.orderBy(F.monotonically_increasing_id()).rowsBetween(0, Window.unboundedFollowing)')
        for col in columns:
            lines.append(f'df = df.withColumn("{col}", F.first(F.col("{col}"), ignorenulls=True).over(w))')
        return "\n".join(lines)

    def _gen_pivot(self, step: dict) -> str:
        pivot_col = step.get("pivot_column", "")
        value_col = step.get("value_column", "")
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.Pivot(...)")
        lines.append(f"# TODO: Review pivot - may need groupBy columns specified")
        lines.append(f'df = df.groupBy().pivot("{pivot_col}").agg(F.first(F.col("{value_col}")))')
        return "\n".join(lines)

    def _gen_unpivot(self, step: dict) -> str:
        columns = step.get("columns", [])
        attr_col = step.get("attribute_column", "Attribute")
        val_col = step.get("value_column", "Value")
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.Unpivot(...)")
        cols_str = ", ".join(f'"{c}"' for c in columns)
        lines.append(f"df = df.unpivot([{cols_str}], {attr_col!r}, {val_col!r})")
        return "\n".join(lines)

    def _gen_unpivot_other(self, step: dict) -> str:
        return self._gen_unpivot(step)

    def _gen_duplicate_column(self, step: dict) -> str:
        src = step.get("source_column", "")
        new = step.get("new_column", "")
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.DuplicateColumn(...)")
        lines.append(f'df = df.withColumn("{new}", F.col("{src}"))')
        return "\n".join(lines)

    def _gen_first_n(self, step: dict) -> str:
        n = step.get("n", 1)
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.FirstN(..., {n})")
        lines.append(f"df = df.limit({n})")
        return "\n".join(lines)

    def _gen_last_n(self, step: dict) -> str:
        n = step.get("n", 1)
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.LastN(..., {n})")
        lines.append(f"# TODO: LastN has no direct PySpark equivalent - requires sorting")
        lines.append(f"df = df.tail({n})  # Returns rows, not DataFrame")
        return "\n".join(lines)

    def _gen_skip(self, step: dict) -> str:
        n = step.get("n", 1)
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.Skip/RemoveFirstN(..., {n})")
        lines.append("# TODO: Skip requires row numbering - adding monotonic ID")
        lines.append('df = df.withColumn("_row_num", F.monotonically_increasing_id())')
        lines.append(f'df = df.filter(F.col("_row_num") >= {n}).drop("_row_num")')
        return "\n".join(lines)

    def _gen_cache(self, step: dict) -> str:
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.Buffer(...)")
        lines.append("df = df.cache()")
        return "\n".join(lines)

    def _gen_transform_columns(self, step: dict) -> str:
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: {self._truncate(step['raw'])}")
        lines.append("# TODO: Table.TransformColumns - review and convert manually")
        return "\n".join(lines)

    def _gen_promote_headers(self, step: dict) -> str:
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append("# M: Table.PromoteHeaders(...)")
        lines.append("# TODO: PromoteHeaders - typically handled at read time with header=True")
        return "\n".join(lines)

    def _gen_remove_last_n(self, step: dict) -> str:
        n = step.get("n", 1)
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# M: Table.RemoveLastN(..., {n})")
        lines.append(f"# TODO: RemoveLastN - no direct equivalent, using count-based approach")
        lines.append(f"_total = df.count()")
        lines.append(f"df = df.limit(_total - {n})")
        return "\n".join(lines)

    def _gen_unknown(self, step: dict) -> str:
        lines = [f"# --- Step: {step['name']} ---"]
        lines.append(f"# TODO: Could not auto-convert this step. Original M code:")
        for raw_line in step["raw"].split("\n"):
            lines.append(f"#   {raw_line}")
        lines.append("# df = df  # Placeholder - implement manually")
        return "\n".join(lines)

    # --- Write ---

    def _generate_write(self, table_name: str) -> str:
        return "\n".join([
            "# --- Write ---",
            'df.write.format("delta") \\',
            '    .mode("overwrite") \\',
            "    .saveAsTable(target_table)",
        ])

    # --- Expression converters ---

    def _convert_condition(self, m_condition: str) -> str:
        """Convert M filter condition to PySpark filter expression."""
        expr = m_condition.strip()

        # Handle null checks
        expr = re.sub(r'\[([^\]]+)\]\s*=\s*null', r'F.col("\1").isNull()', expr)
        expr = re.sub(r'\[([^\]]+)\]\s*<>\s*null', r'F.col("\1").isNotNull()', expr)

        # Handle [Column] = "value" patterns
        expr = re.sub(
            r'\[([^\]]+)\]\s*=\s*"([^"]*)"',
            r'(F.col("\1") == "\2")',
            expr,
        )
        expr = re.sub(
            r'\[([^\]]+)\]\s*<>\s*"([^"]*)"',
            r'(F.col("\1") != "\2")',
            expr,
        )

        # Handle [Column] = number
        expr = re.sub(
            r'\[([^\]]+)\]\s*=\s*(\d+(?:\.\d+)?)',
            r'(F.col("\1") == \2)',
            expr,
        )
        expr = re.sub(
            r'\[([^\]]+)\]\s*<>\s*(\d+(?:\.\d+)?)',
            r'(F.col("\1") != \2)',
            expr,
        )

        # Handle comparison operators
        expr = re.sub(
            r'\[([^\]]+)\]\s*(>=|<=|>|<)\s*(\d+(?:\.\d+)?)',
            r'(F.col("\1") \2 \3)',
            expr,
        )

        # Handle Text.Contains, Text.StartsWith, Text.EndsWith
        expr = re.sub(
            r'Text\.Contains\(\[([^\]]+)\],\s*"([^"]*)"\)',
            r'F.col("\1").contains("\2")',
            expr,
        )
        expr = re.sub(
            r'Text\.StartsWith\(\[([^\]]+)\],\s*"([^"]*)"\)',
            r'F.col("\1").startswith("\2")',
            expr,
        )
        expr = re.sub(
            r'Text\.EndsWith\(\[([^\]]+)\],\s*"([^"]*)"\)',
            r'F.col("\1").endswith("\2")',
            expr,
        )

        # Handle 'and' / 'or' operators
        expr = expr.replace(" and ", " & ")
        expr = expr.replace(" or ", " | ")

        # Handle remaining [Column] references
        expr = re.sub(r'\[([^\]]+)\]', r'F.col("\1")', expr)

        return expr

    def _convert_each_expression(self, m_expr: str) -> str:
        """Convert an M 'each' expression body to PySpark column expression."""
        expr = m_expr.strip()

        # Handle if/then/else → F.when().otherwise()
        if_match = re.match(r'if\s+(.+?)\s+then\s+(.+?)\s+else\s+(.+)', expr, re.DOTALL)
        if if_match:
            cond = self._convert_condition(if_match.group(1))
            then_val = self._convert_value(if_match.group(2).strip())
            else_val = self._convert_value(if_match.group(3).strip())
            return f"F.when({cond}, {then_val}).otherwise({else_val})"

        # Handle [Column] references
        col_match = re.match(r'^\[([^\]]+)\]$', expr)
        if col_match:
            return f'F.col("{col_match.group(1)}")'

        # Handle [Col1] & [Col2] (string concat)
        if "&" in expr and not re.search(r'[*+\-/]', expr):
            parts = expr.split("&")
            converted = [self._convert_value(p.strip()) for p in parts]
            return f"F.concat({', '.join(converted)})"

        # Handle Text.* function calls
        text_match = re.match(r'Text\.(\w+)\((.+)\)', expr)
        if text_match:
            return self._convert_text_function(text_match.group(1), text_match.group(2))

        # Handle arithmetic expressions with [Column] references (e.g., [Amount] * 1.1)
        if re.search(r'\[[^\]]+\]', expr) and re.search(r'[*+\-/]', expr):
            converted = re.sub(r'\[([^\]]+)\]', r'F.col("\1")', expr)
            converted = re.sub(r'#"([^"]+)"', r'F.col("\1")', converted)
            return converted

        # Handle simple column reference
        expr = re.sub(r'\[([^\]]+)\]', r'F.col("\1")', expr)

        # Handle #"Quoted" references
        expr = re.sub(r'#"([^"]+)"', r'F.col("\1")', expr)

        # Handle string literals
        if expr.startswith('"') and expr.endswith('"'):
            return f"F.lit({expr})"

        # Handle numeric literals
        if re.match(r'^-?\d+(\.\d+)?$', expr):
            return f"F.lit({expr})"

        # Fallback
        return f'F.expr("{self._escape_string(expr)}")  # TODO: Review expression'

    def _convert_value(self, val: str) -> str:
        """Convert an M value to PySpark literal or column ref."""
        val = val.strip()
        if val == "null":
            return "F.lit(None)"
        if val.startswith('"') and val.endswith('"'):
            return f"F.lit({val})"
        if re.match(r'^-?\d+(\.\d+)?$', val):
            return f"F.lit({val})"
        col_match = re.match(r'^\[([^\]]+)\]$', val)
        if col_match:
            return f'F.col("{col_match.group(1)}")'
        return f'F.lit("{val}")'

    def _convert_text_function(self, func: str, args: str) -> str:
        """Convert a Text.* function call."""
        if func == "Upper":
            col = self._extract_col_ref(args)
            return f"F.upper({col})"
        elif func == "Lower":
            col = self._extract_col_ref(args)
            return f"F.lower({col})"
        elif func == "Trim":
            col = self._extract_col_ref(args)
            return f"F.trim({col})"
        elif func == "Length":
            col = self._extract_col_ref(args)
            return f"F.length({col})"
        elif func == "Replace":
            parts = args.split(",", 2)
            col = self._extract_col_ref(parts[0])
            old = parts[1].strip() if len(parts) > 1 else '""'
            new = parts[2].strip() if len(parts) > 2 else '""'
            return f"F.regexp_replace({col}, {old}, {new})"
        return f'F.expr("TODO: Text.{func}")  # TODO: Convert manually'

    def _extract_col_ref(self, text: str) -> str:
        """Extract a column reference from text."""
        text = text.strip()
        col_match = re.match(r'\[([^\]]+)\]', text)
        if col_match:
            return f'F.col("{col_match.group(1)}")'
        return f'F.col("{text}")'

    def _convert_aggregation(self, m_agg_expr: str, agg_name: str) -> str:
        """Convert M aggregation expression to PySpark."""
        m_agg_expr = m_agg_expr.strip()

        # List.Sum([Column])
        agg_match = re.match(r'(List\.\w+)\(\[([^\]]+)\]\)', m_agg_expr)
        if agg_match:
            func = get_agg_function(agg_match.group(1))
            col = agg_match.group(2)
            return f'{func}(F.col("{col}")).alias("{agg_name}")'

        # List.Count(each ...)
        if "List.Count" in m_agg_expr:
            return f'F.count("*").alias("{agg_name}")'

        # Table.RowCount
        if "Table.RowCount" in m_agg_expr:
            return f'F.count("*").alias("{agg_name}")'

        return f'F.first(F.lit("TODO")).alias("{agg_name}")  # TODO: {m_agg_expr}'

    # --- Utilities ---

    def _to_snake_case(self, name: str) -> str:
        """Convert a name to snake_case."""
        # Remove special characters
        name = re.sub(r'[^a-zA-Z0-9\s_]', '', name)
        # Replace spaces and camelCase with underscores
        name = re.sub(r'([a-z])([A-Z])', r'\1_\2', name)
        name = re.sub(r'[\s]+', '_', name)
        return name.lower().strip('_')

    def _truncate(self, text: str, max_len: int = 100) -> str:
        """Truncate text for display in comments."""
        text = text.replace("\n", " ").strip()
        if len(text) <= max_len:
            return text
        return text[:max_len] + "..."

    def _py_literal(self, val: str) -> str:
        """Convert an M value to a Python literal string."""
        if val == "null":
            return "None"
        if re.match(r'^-?\d+(\.\d+)?$', val):
            return val
        return f'"{val}"'

    def _escape_string(self, s: str) -> str:
        """Escape a string for embedding in a Python string."""
        return s.replace("\\", "\\\\").replace('"', '\\"')
